### ISSUE TITLE
style.css Bug Report

### ISSUE THREAD

**Issue by pritom007** [pritom007/ollama_chatbot#5]
I have reviewed the provided code, and I could not find any major bugs that would prevent it from functioning as intended. However, I have identified a few potential improvements and best practices you might consider:

1. The CSS code does not include any comments explaining the purpose of different sections or rules. Adding comments can help improve code readability and maintainability.

2. There is a mix of double quotes (") and single quotes (') used for string values. It is a good practice to stick to one style for consistency.

3. The `@media` rule targets a `max-width` of 768px, but it does not have a corresponding `min-width` media query for smaller viewports. You might want to consider adding a `min-width` media query to ensure proper styling on very small viewports.

4. The `--radius` variable is set to 4px, but it is only used in the `.code-header` rule. If you plan to use this variable in other parts of your code, ensure that it is consistent across the entire project.

5. The `.copy-code-button` rule does not include any `:focus` or `:active` states. Adding these states can improve accessibility and user experience.

6. The `.token` rules for syntax highlighting are missing some common token types, such as keywords, functions, and numbers. You might want to include these token types for better readability.

Here's the revised code with the suggested improvements:

```css
:root {
  /* ... same as before ... */
}

body {
  /* ... same as before ... */
}

/* ... other styles ... */

@media (min-width: 300px) and (max-width: 768px) {
  body {
    font-size: calc(12px + (24 - 12) * ((100vw - 300px) / (1600 - 300)));
  }

  /* ... other media queries ... */
}

/* Code block container */
pre[class*="language-"] {
  /* ... same as before ... */
}

/* Code block header */
.code-header {
  /* ... same as before ... */
}

/* Copy code button */
.copy-code-button {
  /* ... same as before ... */
}

/* Copy code button :hover state */
.copy-code-button:hover {
  /* ... same as before ... */
}

/* Copy code button :focus state */
.copy-code-button:focus {
  box-shadow: 0 0 2px 1px var(--accent-color);
}

/* Copy code button :active state */
.copy-code-button:active {
  background-color: #005a9e;
}

/* Syntax Highlighting */
/* Adjust the colors based on the Prism.js theme you choose or custom colors */
.token.operator,
.token.entity,
.token.url,
.language-css .token.string,
.style .token.string,
.token.variable,
.token.function,
.token.keyword,
.token.number {
  color: #9a6e3a;
}

.token.punctuation {
  color: #999;
}

/* ... other Prism.js styles ... */
```
